### ISSUE TITLE
Windows CI environment

### ISSUE THREAD

**Issue by jbalsip** [pawotter/mastodon-api-cs#15]
To help cover some of the platform gaps I've experienced, I would recommend extending CI to include a Windows environment. [AppVeyor](https://ci.appveyor.com/) could be used in addition to Travis, and it is what Microsoft uses in their open source projects.  I'd prioritize this as something nice to have, however, so it can wait if there are more important things to work on first.

**Comment by 53ningen** [comment]
Thank you for teaching me about `AppVeyour` (I didn't know that).
I' will try to add it.
